import { Inter } from "next/font/google";
import "./globals.css";
import TopHeader from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopHeader />
        {children}
        {/* Footer Script Start */}
        <Footer />
        {/* Footer Script ENd */}
      </body>
    </html>
  );
}
